export const AUTHOR_LIST_REQUEST = 'AUTHOR_LIST_REQUEST';
export const AUTHOR_LIST_SUCCESS = 'AUTHOR_LIST_SUCCESS';
export const AUTHOR_LIST_FAIL = 'AUTHOR_LIST_FAIL';

export const AUTHOR_DELETE_REQUEST = 'AUTHOR_DELETE_REQUEST';
export const AUTHOR_DELETE_SUCCESS = 'AUTHOR_DELETE_SUCCESS';
export const AUTHOR_DELETE_FAIL = 'AUTHOR_DELETE_FAIL';